{{- if .Values.pdb.enabled -}}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: binderhub
  labels:
    app: binder
    name: binder
    component: binder
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: binder
      name: binder
      component: binder
      release: {{ .Release.Name }}
{{- end }}
