apiVersion: v1
kind: Service
metadata:
  name: binder
  annotations: {{ .Values.service.annotations | toJson }}
  labels: {{ .Values.service.labels | toJson }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- .Values.service.loadBalancerSourceRanges | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  selector:
    app: binder
    name: binder
    component: binder
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{ if .Values.service.portName -}}
      name: {{ .Values.service.portName }}
      {{- end }}
